// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjilvhmynzrunkjlxtar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqaWx2aG15bnpydW5ramx4dGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTg1MjYsImV4cCI6MjA3MTYzNDUyNn0.vVfmylL31G-Dq5_QIiX3X02RV3ggqIHOJxCodpmQlJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});